spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
    password: imu123
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
server:
  port: 9191